#!/bin/bash

NS='ns-sgfree.elcavlaw.com'
NS1='sdns.myudph.elcavlaw.com'
NS2='sdns.myudp.elcavlaw.com'
NS3='sdns.myudp1.elcavlaw.com'

LOOP_DELAY=1

declare -a HOSTS=('112.198.115.44' '124.6.181.36' '112.198.115.36' '112.198.115.60' '124.6.181.12' '124.6.181.4')

DIG_EXEC="DEFAULT"
CUSTOM_DIG="/data/data/com.termux/files/home/go/bin/fastdig"

# DNS settings
BOOST_QUERIES=3
INITIAL_TTL=30

VER=0.9

# Choose the appropriate dig command
case "${DIG_EXEC}" in
    DEFAULT|D)
        _DIG="$(command -v dig)"
        ;;
    CUSTOM|C)
        _DIG="${CUSTOM_DIG}"
        ;;
    *)
        echo "Invalid value for DIG_EXEC: ${DIG_EXEC}"
        exit 1
        ;;
esac

# Check if the chosen dig command is available
if [ ! "$_DIG" ]; then
    echo "Dig command not found. Please install dig (dnsutils) or check DIG_EXEC and CUSTOM_DIG variables."
    exit 1
fi

endscript() {
    unset NS NS1 NS2 NS3 LOOP_DELAY HOSTS _DIG DIG_EXEC CUSTOM_DIG T R M TTL
    exit 1
}

trap endscript 2 15

check() {
    for T in "${HOSTS[@]}"; do
        for R in "${NS}" "${NS1}" "${NS2}" "${NS3}"; do
            if [[ -z $(timeout -k 10 10 ${_DIG} @${T} ${R}) ]]; then
                M=31
                echo -e "\e[1;${M}m\$ R:${R} D:${T}\e[0m"
            else
                M=32
                echo -e "\e[1;${M}m\$ R:${R} D:${T} - Connected!\e[0m"
            fi
            echo "---------------------------------------"
        done
    done
}

boost_dns() {
    for ((i=0; i<"${#HOSTS[@]}"; i++)); do
        for ((j=0; j<${BOOST_QUERIES}; j++)); do
            TTL=$((INITIAL_TTL + j))
            if ${_DIG} +short +ttl=${TTL} @${HOSTS[$i]} ${A} &>/dev/null; then
                echo "Boosted DNS query for ${HOSTS[$i]} - TTL: ${TTL} - Connected!"
            else
                echo "Boosted DNS query for ${HOSTS[$i]} - TTL: ${TTL}"
            fi
        done
        echo "---------------------------------------"
    done
    wait
}

echo "DNSTT Keep-Alive script <Lantin Nohanih>"
echo -e "DNS List: [\e[1;34m${HOSTS[*]}\e[0m]"
echo "CTRL + C to close script"

[[ "${LOOP_DELAY}" -eq 1 ]] && ((LOOP_DELAY++))

echo "Performing Keep-Alive..."
while true; do
    check
    echo '.--. .-.. . .- ... .     .-- .- .. -'
    sleep "${LOOP_DELAY}"
done
